// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 4/17/2025, 3:36:39 PM
const configMerger = require("/Users/loukavandertaelen/Documents/Nuxt-TheLibrary-Louka/node_modules/@nuxtjs/tailwindcss/dist/runtime/merger.mjs");

const inlineConfig = {"content":[],"theme":{"extend":{}},"plugins":[]};

const config = [
require("./../tailwind.config.js")
].reduce((prev, curr) => configMerger(curr, prev), configMerger(inlineConfig, { content: ["/Users/loukavandertaelen/Documents/Nuxt-TheLibrary-Louka/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/loukavandertaelen/Documents/Nuxt-TheLibrary-Louka/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/loukavandertaelen/Documents/Nuxt-TheLibrary-Louka/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/loukavandertaelen/Documents/Nuxt-TheLibrary-Louka/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/loukavandertaelen/Documents/Nuxt-TheLibrary-Louka/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/loukavandertaelen/Documents/Nuxt-TheLibrary-Louka/plugins/**/*.{js,ts,mjs}","/Users/loukavandertaelen/Documents/Nuxt-TheLibrary-Louka/composables/**/*.{js,ts,mjs}","/Users/loukavandertaelen/Documents/Nuxt-TheLibrary-Louka/utils/**/*.{js,ts,mjs}","/Users/loukavandertaelen/Documents/Nuxt-TheLibrary-Louka/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/loukavandertaelen/Documents/Nuxt-TheLibrary-Louka/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/loukavandertaelen/Documents/Nuxt-TheLibrary-Louka/app.config.{js,ts,mjs}"] }));

module.exports = (() => {const cfg=config;cfg["darkMode"] = ["selector","[class~=\"dark-mode\"]"];;return cfg;})()
